---
# =============================================================================
# Kustomization - Transaction Service
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orange-wallet

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml

images:
  - name: asia-southeast2-docker.pkg.dev/orange-wallet/orange-wallet-registry/transaction-service
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/name: transaction-service
      app.kubernetes.io/part-of: orange-wallet
      app.kubernetes.io/managed-by: kustomize
